---
title: "SIRS metapopulation model"
author: "Matthew Hoyle"
output: html_notebook
---
SIRS metapopulation model with flexible patch size and number

```{r}
rm(list = ls())

library(GillespieSSA)
library(tidyverse)
```


# Define Paramenters
```{r}
patchPopSize <-     c(500, 200, 100, 100)    # Patch size
U <- length(patchPopSize)                    # Number of patches
initial_infected <-  as.vector(rmultinom(1, 1, rep(0.5, U)))   # Initial infected (initial infected patch randomly generated)
initial_infected_patch <- which(initial_infected > 0)                 # Number of patches
simName <- "SIRS metapopulation model"      # Simulation name
tf <- 500                                   # Final time

#Collect parameters
parms <- list(
  sigma = 1/20,                        # E to I rate
  gamma = 0.1,                         # I to R rate
  omega = 0.005                         # R to S rate
) 

#Transmission terms
beta = 0.8
within_pop_contact = 1
between_pop_contact = 0.005/U #normalised by number of patches 


for(i in 1:U){
  for(j in 1:U){
    parms[[paste0("beta_",i,i)]] = within_pop_contact*beta
    parms[[paste0("beta_",j,i)]] = between_pop_contact*beta
    parms[[paste0("beta_",j,j)]] = within_pop_contact*beta
  }
  parms[[paste0("N", i)]] = patchPopSize[i]
}
```

# Create the named initial state vector for the U-patch system.
```{r}
x0 <- unlist(lapply(
  seq_len(U), 
  function(i){ 
  c(patchPopSize[i] - initial_infected[i], initial_infected[i], 0, patchPopSize[i])
  }
  ))

names(x0) <- unlist(lapply(seq_len(U), function(i) paste0(c("S","E","I", "N"), i)))
```


# Define the state change matrix for a single patch
```{r}
nu <- matrix(c( -1,  0,  0, +1,  # S
                +1, -1,  0,  0, # E
                 0, +1, -1,  0, # I
                 0,  0,  0,  0), # N
             nrow=4,byrow=TRUE)
```


# Define propensity functions
```{r}
# Mass-action
a <-
  unlist(lapply(
    seq_len(U),
    function(patch) {
      i <- patch
      patches <- 1:U
      #j <- if (patch == 1) U else patch - 1
      other_patches <- patches[-i]
      patch_beta <- c()
      for(k in (1:(U-1))){
        patch_beta[k] = paste0("+(beta_", other_patches[k],i, "*I", other_patches[k], "/N", other_patches[k], ")*S", i)
      }
      c(
        paste0("(beta_", i, i, "*I", i,"/N", i, ")*S",i, paste0(patch_beta, collapse="")),
        paste0("sigma*E", i),
        paste0("gamma*I", i),                     # Recovery from infection
        paste0("omega*(N", i, "-S", i, "-I", i,"-E", i, ")")       # Loss of immunity
      )
    }
  ))
```


# Run simulations with the Direct method
```{r}
# set.seed(1)
out <- ssa(
  x0 = x0,
  a = a,
  nu = nu,
  parms = parms,
  tf = tf,
  method = ssa.d(),
  simName = simName,
  verbose = FALSE,
  consoleInterval = 1
)
```

# Plots
```{r}
# Built-in plotting function
# ssa.plot(out, by = 2, show.title = TRUE, show.legend = T) #all states

## Extra Plots
plot_data <- out$data %>%
  as_tibble() %>%
  pivot_longer(!t, names_to = "ID", values_to = "count") %>%
  separate(ID, 
           into = c("state", "patch"), 
           sep = "(?<=[A-Za-z])(?=[0-9])") %>%
  mutate(state = factor(state, levels = c("S", "E", "I", "N"))) %>%
  filter(state != "N")

ggplot(data = plot_data, aes(x=t, y=count, colour=state))+
  geom_line()+
  facet_wrap(~factor(patch, levels = unique(patch)) ,ncol = 1, scales = "free_y")+
  labs(x="Time",
       y="Frequency")+
  theme_bw()
```

## Table showing extinction/transmission info for each patch
```{r}
extinct_data <- out$data %>%
  as_tibble() %>%
  slice_max(t) %>%
  distinct() %>%
  pivot_longer(!t, names_to = "ID", values_to = "count") %>%
  separate(ID, 
           into = c("state", "patch"), 
           sep = "(?<=[A-Za-z])(?=[0-9])") %>%
  mutate(state = factor(state, levels = c("S", "E", "I", "N")),
         persist = case_when(state=="I" & count > 0 ~ T, 
                             state=="I" & count == 0 ~ F)) %>%
  drop_na() %>%
  select(patch, count, persist)
extinct_data
```


```{r}
## Run multiple simulations and saving output
num_sims <- 100
sim_list <- list()
sim_list <- vector("list", length = num_sims)
sim_plot_list <- vector("list", length = num_sims)


for (i in 1:num_sims){
  #set.seed(i)
  out_2 <- ssa(
    x0 = x0,
    a = a,
    nu = nu,
    parms = parms,
    tf = tf,
    method = ssa.d(),
    simName = simName,
    verbose = FALSE,
    consoleInterval = 1
  )
  
  
# Extract output data for plotting
  sim_plot <- out_2$data %>%
      as_tibble() %>%
      pivot_longer(!t, names_to = "ID", values_to = "count") %>%
      separate(ID, 
           into = c("state", "patch"), 
           sep = "(?<=[A-Za-z])(?=[0-9])") %>%
      mutate(state = factor(state, levels = c("S", "E", "I", "N")),
             sim = i) %>%
      filter(state != "N")
  
  sim_plot_list[[i]] <- sim_plot
  
# Extract Final time point from output data
  sim_data <- out_2$data %>%
    as_tibble() %>%
    slice_max(t) %>%
    distinct() %>%
    pivot_longer(!t, names_to = "ID", values_to = "count") %>%
    separate(ID, 
             into = c("state", "patch"), 
             sep = "(?<=[A-Za-z])(?=[0-9])") %>%
    mutate(state = factor(state, levels = c("S", "E", "I", "N")),
           persist = case_when(state=="I" & count > 0 ~ T, 
                               state=="I" & count == 0 ~ F),
           sim = i) %>%
    drop_na() %>%
    select(sim, patch, count, persist)
  
  sim_list[[i]] <- sim_data
}
sim_plot_output <- bind_rows(sim_plot_list)

sim_output <- bind_rows(sim_list)
```


```{r}
# Summary table of endpoint data
sim_summary <- sim_output %>%
  group_by(sim) %>%
  summarise(total_p_persist = sum(persist, na.rm = T), 
            total_infecteds = sum(count)) %>%
  mutate(percent_P_persist = total_p_persist/(U)*100, 
         persist = case_when(total_infecteds > 0 ~ T, 
                               total_infecteds == 0 ~ F))
sim_summary
```

```{r}
# In how many simulations did the pathogen persist to simulation end point?
sum(sim_summary$persist)
```

## Plot multiple sims
```{r}
sim_plot_output <- sim_plot_output %>%
  filter(state=="I")

ggplot(data = sim_plot_output, aes(x=t, y=count, colour=as.factor(sim)))+
  geom_line(alpha = 0.5)+
  facet_wrap(~factor(patch, levels = unique(patch)) ,ncol = 1, scales = "free_y")+
  labs(x="Time",
       y="Frequency")+
  theme_bw()
```


